### ISSUE TITLE
Donations are not created.

### ISSUE THREAD

**Issue by Bevilacqua** [includedavis/farmdavis#15]
@ottopchen I started working on updating the search feature but whenever I try to create a new donation nothing seems to happen, no error message or anything, it just doesn't get added to the table. Could you try on your end and see if it's a problem. Trying to figure out if it's something I did.

**Comment by ottopchen** [comment]
@Bevilacqua Are you assigning a category to the donation? A donation requires a Date, Category, and Quantity, and it won't be created if any of those are missing.

**Comment by Bevilacqua** [comment]
I'm dumb completely forgot the date. We should definitely have error messages for that though.

**Comment by ottopchen** [comment]
I don't have error messages right now because those validations/requirements are what prevents empty donations from being added. So when you only fill 2 of the 10 rows, the last 8 rows aren't added because they don't have a date, category, and quantity, and I didn't want a bunch of error messages popping up when a user is just adding a few donations. Not sure what the best way to solve this is yet.
